
package queraton;

import fuentes.*;
import java.awt.List;
import java.awt.event.KeyEvent;  // Libreria que sirve para preguntar que tecla se presiono. Libreria de eventos para teclas
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tp02.ejercicio2.ListaEnlazadaGenerica;
import tp02.ejercicio2.ListaGenerica;


/**
 *
 * @author DRAGON Z
 */
public class Ventana extends javax.swing.JFrame {

    private ListaGenerica<JLabel> listaLabels=new ListaEnlazadaGenerica<>();
    private Juntada J= new Juntada();
    private ListaEnlazadaGenerica<Persona> listaPersonas = J.getLis();
    CustomFonts cf = new CustomFonts(); //Creo una instancia cf para agregar una fuente mia, que esta en la clase CustomFonts
    int i=0;// Para poner el nombre Alien1 Alien2
    
    public Ventana() {      
        initComponents();
        setLocationRelativeTo(null); // Para centrar la ventana en el medio
        NombrePersona.requestFocus(); //Se posiciona en el nombre
        listaLabels.comenzar();
        listaPersonas.comenzar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombrePersona = new javax.swing.JTextField();
        LoQuePuso = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        LabelPuso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(cf.MyFont(1, 28f));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Ingresar el nombre de la Persona y cuanto es lo que puso");

        NombrePersona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombrePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePersonaActionPerformed(evt);
            }
        });
        NombrePersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombrePersonaKeyTyped(evt);
            }
        });

        LoQuePuso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoQuePusoActionPerformed(evt);
            }
        });
        LoQuePuso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoQuePusoKeyTyped(evt);
            }
        });

        Agregar.setBackground(new java.awt.Color(51, 153, 255));
        Agregar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-usuariosa.png"))); // NOI18N
        Agregar.setBorderPainted(false);
        Agregar.setContentAreaFilled(false);
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Agregar.setName(""); // NOI18N
        Agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-agregado.png"))); // NOI18N
        Agregar.setRequestFocusEnabled(false);
        Agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-usuariosok.png"))); // NOI18N
        Agregar.setVerifyInputWhenFocusTarget(false);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        LabelNombre.setText("Nombre");

        LabelPuso.setText("Cuanto puso?");

        Panel.setLayout(new java.awt.GridLayout(0, 3, 50, 50));
        jScrollPane1.setViewportView(Panel);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPuso)
                            .addComponent(LabelNombre)
                            .addComponent(NombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoQuePuso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(425, 425, 425)
                        .addComponent(jButton1)
                        .addContainerGap(479, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(LabelPuso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoQuePuso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePersonaActionPerformed

    }//GEN-LAST:event_NombrePersonaActionPerformed

    private void LoQuePusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoQuePusoActionPerformed

        
     
        
       
    }//GEN-LAST:event_LoQuePusoActionPerformed

    
    public void AgregarUsuario(){
        JLabel textoNombre= new javax.swing.JLabel();
        JLabel textoPuso= new javax.swing.JLabel();
        JButton usuario = new JButton();
        
        //Lo de abajo podria crear una clase, caracteristicas del boton icono
        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-agregado.png")));
        usuario.setBorderPainted(false);
        usuario.setContentAreaFilled(false);
        usuario.setOpaque(false);
        
        
        String nombre= this.NombrePersona.getText(); //NombrePersona es el campo Leabel del nombre
                                                                   
        double puso;
        
        Panel.add(usuario);
        Panel.add(textoNombre);
        Panel.add(textoPuso);
       
        
        listaLabels.agregarFinal(textoNombre);
        listaLabels.agregarFinal(textoPuso);

        textoNombre.setFont(cf.MyFont(1, 28f)); // Le envio un mensaje al objeto cf (CustomField) para indicar las caracteristicas de la fuente que agregue
        textoPuso.setFont(cf.MyFont(1, 28f));
        
        
        if(this.LoQuePuso.getText().isEmpty()){ //LoQuePuso es el campo Leabel del monto //Si el label esta vacio setear con cero

          puso=0;
          textoPuso.setText("0");
        //  textoNombre.setText("");   //Le pongo nombre al campo Lebel
        }
        else{ // Si no esta vacio convertir el texto a numero y operar
          puso = Integer.parseInt(this.LoQuePuso.getText()); // Integer.parseInt convierte el texto que viene en un numero para poder realizar los calculos
          
          textoPuso.setText(this.LoQuePuso.getText());  //Le pongo nombre al campo loquepuso
                 
        }
        
        if(this.NombrePersona.getText().isEmpty()){
           i=i+1;
           String iNombre=Integer.toString(i);  //Convierte entero a string
           textoNombre.setText("Alien "+iNombre);  //Para poner los nombres alien
        }
        else{
        textoNombre.setText(nombre);   //Le pongo nombre al campo Lebel
        }
      //  Persona P = new Persona(nombre,puso);
      //  listaPersonas.agregarFinal(P);
        J.agragarIntegrante(nombre,puso);
        }
    
    
    
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        //Evento que genera presionar el boton
        this.AgregarUsuario();
        NombrePersona.setText(""); // Reinicio los campos a vacio
        LoQuePuso.setText("");
        NombrePersona.requestFocus();
    }//GEN-LAST:event_AgregarActionPerformed

    private void LoQuePusoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoQuePusoKeyTyped

          char caracterCapturado = evt.getKeyChar();  // Le pide al campo Leabel el primer caracter que quiero ingresar
          
          if(Character.isLetter(caracterCapturado)){  // Pregunto si es una letra con isLetter, si quiero lo contrario pregunto isDigit
            getToolkit().beep();   // Hace un sonido
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Solo se puede ingresar un monto"); // Muestra cartel en pantalla
          }
          
          if(caracterCapturado==KeyEvent.VK_ENTER){ //Pregunto si se presiono la tecla ENTER
           Agregar.doClick();           
          }
          
    }//GEN-LAST:event_LoQuePusoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombrePersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombrePersonaKeyTyped
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            LoQuePuso.requestFocus();
        
        }
    }//GEN-LAST:event_NombrePersonaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPuso;
    private javax.swing.JTextField LoQuePuso;
    private javax.swing.JTextField NombrePersona;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
